import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import openaiRouter from "./openai/index.js";
import visionRouter from "./vision/index.js";
import insightsRouter from "./insights/index.js";
import authRouter from "./auth/index.js";
import barcodeRouter from "./barcode/index.js";
import upcRouter from "./upc/index.js";
import squareRouter from "./square/index.js";
import storehubRouter from "./storehub/index.js";
import adminRouter from "./admin/index.js";
import businessesRouter from "./businesses/index.js";
import onboardingRouter from "./onboarding/index.js";
import analyticsRouter from "./analytics/index.js";
import integrationsRouter from "./integrations/index.js";
import tipsRouter from "./tips/index.js";
import predictionsRouter from "./predictions/index.js";
import cashflowRouter from "./cashflow/index.js";
import customersRouter from "./customers/index.js";
import supplierIntelligenceRouter from "./suppliers/intelligence.js";
import voiceRouter from "./voice/index.js";
import portalRouter from "./portal/index.js";
import inviteRouter from "./auth/invite.js";
import sessionsRouter from "./auth/sessions.js";
import mfaRouter from "./auth/mfa.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/openai",                 openaiRouter);
router.use("/vision",                 visionRouter);
router.use("/insights",               insightsRouter);
router.use("/auth",                   authRouter);
router.use("/barcode",                barcodeRouter);
router.use("/upc",                    upcRouter);
router.use("/square",                 squareRouter);
router.use("/storehub",               storehubRouter);
router.use("/admin",                  adminRouter);
router.use("/businesses",             businessesRouter);
router.use("/onboarding",             onboardingRouter);
router.use("/analytics",              analyticsRouter);
router.use("/integrations",           integrationsRouter);
router.use("/tips",                   tipsRouter);
router.use("/predictions",            predictionsRouter);
router.use("/cashflow",               cashflowRouter);
router.use("/customers",              customersRouter);
router.use("/suppliers",              supplierIntelligenceRouter);
router.use("/voice",                  voiceRouter);
router.use("/portal",                 portalRouter);
router.use("/auth/invite",            inviteRouter);
router.use("/auth/sessions",          sessionsRouter);
router.use("/auth/mfa",               mfaRouter);

export default router;
