/**
 * tipsService.ts — Smart Tips Engine
 *
 * Manages AI-powered tip generation, caching, and state (done/dismissed).
 * Tips are generated by Claude via /api/tips/generate and cached for 24h.
 */

import { getDashboardSummary, getProducts, getSales, getExpenses, getSuppliers, getUserProfile } from "./dataService";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SmartTip {
  id: string;
  title: string;
  explanation: string;
  action: string;
  urgency: "critical" | "high" | "medium" | "low";
  estimatedImpact: string;
  category: "inventory" | "pricing" | "sales" | "suppliers" | "employees" | "cashflow" | "seasonal" | "compliance";
  emoji: string;
  // Local state (not from API)
  status?: "active" | "done" | "dismissed";
  provenRight?: boolean;       // marked as "Claude was right" after the fact
  generatedAt?: string;
}

export interface WeeklySummary {
  weekSummary: string;
  insights: Array<{
    title: string;
    finding: string;
    recommendation: string;
    category: string;
  }>;
  generatedAt: string;
}

// ─── Storage keys ─────────────────────────────────────────────────────────────

const TIPS_CACHE_KEY       = "storehub_smart_tips";
const TIPS_STATE_KEY       = "storehub_tips_state";    // done/dismissed per tip id
const WEEKLY_CACHE_KEY     = "storehub_weekly_summary";
const TIPS_CACHE_TTL_MS    = 24 * 60 * 60 * 1000;     // 24 hours
const WEEKLY_CACHE_TTL_MS  = 7  * 24 * 60 * 60 * 1000; // 7 days

// ─── Cache helpers ────────────────────────────────────────────────────────────

interface TipsCache {
  tips: SmartTip[];
  generatedAt: string;
}

interface TipState {
  status: "active" | "done" | "dismissed";
  provenRight?: boolean;
  actedAt?: string;
}

function readCache(): TipsCache | null {
  try {
    const raw = localStorage.getItem(TIPS_CACHE_KEY);
    if (!raw) return null;
    const cache = JSON.parse(raw) as TipsCache;
    const age = Date.now() - new Date(cache.generatedAt).getTime();
    return age > TIPS_CACHE_TTL_MS ? null : cache;
  } catch { return null; }
}

function writeCache(tips: SmartTip[], generatedAt: string) {
  localStorage.setItem(TIPS_CACHE_KEY, JSON.stringify({ tips, generatedAt }));
}

function readTipStates(): Record<string, TipState> {
  try {
    return JSON.parse(localStorage.getItem(TIPS_STATE_KEY) ?? "{}");
  } catch { return {}; }
}

function writeTipStates(states: Record<string, TipState>) {
  localStorage.setItem(TIPS_STATE_KEY, JSON.stringify(states));
}

function readWeeklyCache(): (WeeklySummary & { generatedAt: string }) | null {
  try {
    const raw = localStorage.getItem(WEEKLY_CACHE_KEY);
    if (!raw) return null;
    const cache = JSON.parse(raw) as WeeklySummary & { generatedAt: string };
    const age = Date.now() - new Date(cache.generatedAt).getTime();
    return age > WEEKLY_CACHE_TTL_MS ? null : cache;
  } catch { return null; }
}

// ─── Data collection ──────────────────────────────────────────────────────────

async function collectStoreData(): Promise<Record<string, unknown>> {
  const profile = await getUserProfile();
  const [summary, products, sales, expenses, suppliers] = await Promise.all([
    getDashboardSummary(profile).catch(() => null),
    getProducts().catch(() => []),
    getSales().catch(() => []),
    getExpenses().catch(() => []),
    getSuppliers().catch(() => []),
  ]);

  // Last 30 days of sales
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - 30);
  const recentSales = sales.filter(s => new Date(s.createdAt) >= cutoff);

  // Product performance
  const productSales: Record<string, number> = {};
  recentSales.forEach(sale => {
    sale.items.forEach((item: any) => {
      productSales[item.productName] = (productSales[item.productName] ?? 0) + item.quantity;
    });
  });

  // Low stock products
  const lowStock = products.filter(p => p.quantity <= p.lowStockThreshold);
  const outOfStock = products.filter(p => p.quantity === 0);

  // Revenue last 30 days
  const revenue30d = recentSales.reduce((sum, s) => sum + s.total, 0);
  const expenses30d = expenses
    .filter(e => new Date(e.date) >= cutoff)
    .reduce((sum, e) => sum + e.amount, 0);

  // Day-of-week sales pattern
  const salesByDay: Record<string, number> = {};
  recentSales.forEach(s => {
    const day = new Date(s.createdAt).toLocaleDateString("en-US", { weekday: "long" });
    salesByDay[day] = (salesByDay[day] ?? 0) + s.total;
  });

  return {
    store: {
      name: profile?.storeName,
      type: profile?.businessType,
      category: profile?.businessCategory,
      staffCount: profile?.staffCount ?? profile?.storeSize,
      currentSystem: profile?.currentSystem,
      goal: profile?.goal,
      painPoints: profile?.painPoints,
      location: profile?.stateName,
    },
    inventory: {
      totalProducts: products.length,
      outOfStockCount: outOfStock.length,
      outOfStockProducts: outOfStock.map(p => ({ name: p.name, category: p.category })),
      lowStockCount: lowStock.length,
      lowStockProducts: lowStock.map(p => ({
        name: p.name, quantity: p.quantity, threshold: p.lowStockThreshold, category: p.category,
      })),
      topProductsBySales: Object.entries(productSales)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(([name, qty]) => ({ name, unitsSold: qty })),
    },
    sales: {
      last30Days: {
        totalRevenue: revenue30d,
        transactionCount: recentSales.length,
        averageTicket: recentSales.length > 0 ? revenue30d / recentSales.length : 0,
      },
      salesByDayOfWeek: salesByDay,
      today: summary ? {
        revenue: summary.todayRevenue,
        expenses: summary.todayExpenses,
        profit: summary.todayProfit,
        transactionCount: summary.todaySalesCount,
      } : null,
    },
    expenses: {
      last30Days: expenses30d,
      profitMargin30d: revenue30d > 0 ? ((revenue30d - expenses30d) / revenue30d * 100).toFixed(1) + "%" : "N/A",
      byCategory: expenses
        .filter(e => new Date(e.date) >= cutoff)
        .reduce((acc: Record<string, number>, e) => {
          acc[e.category] = (acc[e.category] ?? 0) + e.amount;
          return acc;
        }, {}),
    },
    suppliers: {
      count: suppliers.length,
      names: suppliers.map(s => s.name),
    },
    currentDate: new Date().toISOString(),
    dayOfWeek: new Date().toLocaleDateString("en-US", { weekday: "long" }),
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

/** Get current tips (from cache), merged with their done/dismissed state. */
export function getCachedTips(): SmartTip[] | null {
  const cache = readCache();
  if (!cache) return null;
  const states = readTipStates();
  return cache.tips.map(tip => ({
    ...tip,
    status: states[tip.id]?.status ?? "active",
    provenRight: states[tip.id]?.provenRight ?? false,
    generatedAt: cache.generatedAt,
  }));
}

/** Generate fresh tips from Claude (calls /api/tips/generate). */
export async function generateTips(force = false): Promise<SmartTip[]> {
  if (!force) {
    const cached = getCachedTips();
    if (cached) return cached;
  }

  const states = readTipStates();
  const dismissedIds = Object.entries(states)
    .filter(([, s]) => s.status === "dismissed")
    .map(([id]) => id);

  const storeData = await collectStoreData();

  const res = await fetch("/api/tips/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ storeData, dismissedTipIds: dismissedIds }),
    credentials: "include",
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: "Network error" }));
    throw new Error(err.error ?? "Failed to generate tips");
  }

  const { tips, generatedAt } = await res.json() as { tips: SmartTip[]; generatedAt: string };

  // Keep existing state for tips that reappear with same id
  writeCache(tips, generatedAt);

  return tips.map(tip => ({
    ...tip,
    status: states[tip.id]?.status ?? "active",
    provenRight: states[tip.id]?.provenRight ?? false,
    generatedAt,
  }));
}

/** Mark a tip as done. */
export function markTipDone(tipId: string) {
  const states = readTipStates();
  states[tipId] = { status: "done", actedAt: new Date().toISOString() };
  writeTipStates(states);
}

/** Dismiss a tip (Claude learns not to repeat it). */
export function dismissTip(tipId: string) {
  const states = readTipStates();
  states[tipId] = { status: "dismissed", actedAt: new Date().toISOString() };
  writeTipStates(states);
}

/** Mark a tip as "Claude was right" (trust builder). */
export function markTipProvenRight(tipId: string) {
  const states = readTipStates();
  const existing = states[tipId] ?? { status: "done" };
  states[tipId] = { ...existing, provenRight: true };
  writeTipStates(states);
}

/** Get weekly summary (cached for 7 days). */
export async function getWeeklySummary(force = false): Promise<WeeklySummary | null> {
  if (!force) {
    const cached = readWeeklyCache();
    if (cached) return cached;
  }

  // Only generate on Mondays (or force)
  const isMonday = new Date().getDay() === 1;
  if (!isMonday && !force) return readWeeklyCache();

  const storeData = await collectStoreData();

  const res = await fetch("/api/tips/weekly", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ storeData }),
    credentials: "include",
  });

  if (!res.ok) return readWeeklyCache();

  const { summary, generatedAt } = await res.json();
  const full = { ...summary, generatedAt };
  localStorage.setItem(WEEKLY_CACHE_KEY, JSON.stringify(full));
  return full;
}

/** Stream a follow-up chat response for a tip. */
export async function streamTipChat(
  tip: SmartTip,
  question: string,
  onChunk: (text: string) => void,
  onDone: () => void,
): Promise<void> {
  const storeData = await collectStoreData();

  const res = await fetch("/api/tips/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ tip, question, storeData }),
    credentials: "include",
  });

  if (!res.ok || !res.body) {
    onChunk("Sorry, I couldn't connect to Claude right now. Please try again.");
    onDone();
    return;
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    const text = decoder.decode(value);
    const lines = text.split("\n");
    for (const line of lines) {
      if (!line.startsWith("data: ")) continue;
      try {
        const data = JSON.parse(line.slice(6));
        if (data.content) onChunk(data.content);
        if (data.done) { onDone(); return; }
      } catch { /* skip */ }
    }
  }
  onDone();
}

/** How long ago were tips last generated? */
export function tipsAge(): string | null {
  const cache = readCache();
  if (!cache) return null;
  const ms = Date.now() - new Date(cache.generatedAt).getTime();
  const hrs = Math.floor(ms / 3_600_000);
  const mins = Math.floor((ms % 3_600_000) / 60_000);
  if (hrs >= 1) return `${hrs}h ago`;
  return `${mins}m ago`;
}
