source "https://rubygems.org"

gem "fastlane", "~> 2.225"
gem "fastlane-plugin-increment_build_number_in_plist", "~> 0.1" rescue nil

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
